# Generated by Django 3.2.7 on 2021-10-06 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0003_auto_20211005_1623"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="author_user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author_username",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
