# Generated by Django 3.2.7 on 2021-10-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_auto_20211012_1413"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="type",
            field=models.CharField(
                choices=[
                    (1, "Site Web"),
                    (2, "Application Android"),
                    (3, "Application IOS"),
                ],
                max_length=1,
            ),
        ),
    ]
