# Generated by Django 3.2.7 on 2021-10-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_project_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="type",
            field=models.CharField(
                choices=[
                    ("1", "Site Web"),
                    ("2", "Application Android"),
                    ("3", "Application IOS"),
                ],
                max_length=30,
            ),
        ),
    ]
