# Generated by Django 3.2.7 on 2021-10-13 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_rename_author_user_id_project_author_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="author_user_id",
            new_name="author_user",
        ),
        migrations.RenameField(
            model_name="issue",
            old_name="assignee_user_id",
            new_name="assignee_user",
        ),
        migrations.RenameField(
            model_name="issue",
            old_name="author_user_id",
            new_name="author_user",
        ),
    ]
