# Generated by Django 3.2.7 on 2021-10-13 14:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0015_auto_20211013_1249"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="contributor",
            unique_together={("user", "project_id")},
        ),
    ]
