# Generated by Django 3.2.7 on 2021-10-13 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_alter_contributor_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contributor",
            old_name="project_id",
            new_name="project",
        ),
    ]
