# Generated by Django 3.2.7 on 2021-10-13 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_rename_project_id_contributor_project"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="contributor",
            unique_together=set(),
        ),
    ]
