# Generated by Django 3.2.7 on 2021-10-13 14:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0021_alter_contributor_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="contributor",
            unique_together={("user", "project_id")},
        ),
    ]
