# Generated by Django 3.2.7 on 2021-10-13 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_alter_contributor_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contributor",
            options={"ordering": ["-permission"]},
        ),
    ]
