# Generated by Django 3.2.7 on 2021-10-14 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_alter_issue_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="issue_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="api.issue",
            ),
        ),
    ]
